name: todo_satrirat
description: Todo app for Satrirat.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <4.0.0'

isar_version: &isar_version 3.1.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^7.4.0
  isar: *isar_version
  isar_flutter_libs: *isar_version
  path_provider: ^2.0.15
  flutter_bloc: ^8.0.0
  bloc: ^8.0.0
  easy_debounce: ^2.0.3
  equatable: ^2.0.5
  day: ^0.8.0
  file_picker: ^5.3.2
  flutter_image_compress: ^2.0.3
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: *isar_version
  build_runner: any
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
